### ISSUE TITLE
goesimage needs to call 'xfdesktop --quit' in case of xfce4, or use nitrogen for wallpepr switching, otherwise the wallpaper doesn't change in DEs

### ISSUE THREAD

**Issue by yurivict** [pigmonkey/goesimage#3]
See my question and their answer here: https://bugzilla.xfce.org/show_bug.cgi?id=15475

What should be done: detect that xfce4 session is running (DESKTOP_SESSION=xfce) and call 'xfdesktop --quit' in that case before running ```feh```.

**Comment by yurivict** [comment]
A better solution, based on their suggestion in the above link, is to use ```nitrogen``` for wallpaper switching. ```nitrogen``` already supports ```xfce4``` and other DEs: https://github.com/l3ib/nitrogen/blob/master/src/SetBG.cc#L35

**Comment by pigmonkey** [comment]
I don't want to get into the game of supporting a bunch of different desktop environments and wallpaper programs. Even feh probably shouldn't be in the script, but I'm bias because that's the one I use.

Instead I provide the `-o` flag, which outputs the filename of the final image and doesn't try to change the background. You can do something like:

    $ nitrogen $(goesimage -w -e -o)

The output filename is always the same, so you don't actually even need to capture the output. If you want something with more error checking, you could do:

    if goesimage -w -e -o; then
        nitrogen "$HOME"/.cache/goesimage/latest.jpg
    fi

**Comment by yurivict** [comment]
This works, thanks!
